services:
  remote-gui:
    image: anylogco/remote-gui:latest
    container_name: remote-gui
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
    volumes:
      - image-vol:/app/CLI/local-cli-backend/static/
      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/