services:
  remote-gui:
    image: anylogco/remote-gui:beta
    container_name: remote-gui
    restart: always
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8000
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
    volumes:
      - image-vol:/app/CLI/local-cli-backend/static/
      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/
#      - cli-plugins-frontend:CLI/local-cli-fe-full/src/plugins/
#      - cli-plugins-backend:CLI/local-cli-backend/plugins/
volumes:
  image-vol:
  usr-mgm-vol:
#  cli-plugins-frontend:
#  cli-plugins-backend:


