services:
  remote-gui:
    image: anylogco/remote-gui:beta2
    container_name: remote-gui
    restart: always
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: http://172.236.61.154:8000
    ports:
      - 3001:3001
      - 8000:8000
    volumes:
      - image-vol:/app/CLI/local-cli-backend/static/
      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/
      - report-configs:/app/CLI/local-cli-backend/plugins/reportgenerator/templates
volumes:
  image-vol:
  usr-mgm-vol:
  report-configs: